### ISSUE TITLE
Trying to compile mod_vroot with the current proftpd master

### ISSUE THREAD

**Issue by Castaglia** [Castaglia/proftpd-mod_vroot#7]
Copying this from [Issue#53](https://github.com/proftpd/proftpd/issues/153), for @tspicer.

Attempting to compile the latest in proftpd git with the latest in mod_vroot and the follwing compile errors are showing up. This has only occurred recently. Last time I ran this was about a month ago without incident.

This is on Centos7

    gcc -DHAVE_CONFIG_H -DLINUX -I.. -I../include -I/usr/include -I/usr/include/mysql -I/usr/include/mysql -DBAN_LIST_MAXSZ=8096 -Wall -c mod_vroot.c
    mod_vroot.c: In function 'set_vrootserverroot':
    mod_vroot.c:1518:19: warning: dereferencing 'void ' pointer [enabled by default]
    if (cmd->argv[1][pathlen - 1] != '/') {
    ^
    mod_vroot.c:1518:3: error: void value not ignored as it ought to be
    if (cmd->argv[1][pathlen - 1] != '/') {
    ^
    make[1]: ** [mod_vroot.o] Error 1
    make[1]: Leaving directory `/tmp/proftpd/modules'
    make: *** [modules] Error 2

**Comment by Castaglia** [comment]
Fixed in master.  Thanks!

**Comment by pghmcfc** [comment]
Hi TJ, any chance of a new release of mod_vroot to include all the changes since v0.9.4, since it doesn't build with 1.3.6?

**Comment by Castaglia** [comment]
What are the current build issues/errors you see?  What are the commands you're currently using?

**Comment by pghmcfc** [comment]
The latest release tarball for mod_vroot is v0.9.4, which pre-dates the API changes in 1.3.6. If I patch it with commits from git, it builds fine. I'd just prefer to see a v0.9.5 release so I don't have to do the patching.

**Comment by Castaglia** [comment]
Done; see https://github.com/Castaglia/proftpd-mod_vroot/releases/tag/v0.9.5
